[package]
name = "day-19"
version = "0.1.0"
edition = "2021"

[dependencies]
code-timing-macros.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day-19-bench"
path = "benches/benchmarks.rs"
harness = false