[package]
name = "day-18"
version = "0.1.0"
edition = "2021"

[dependencies]
code-timing-macros.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day-18-bench"
path = "benches/benchmarks.rs"
harness = false