[package]
name = "day-13"
version = "0.1.0"
edition = "2021"

[dependencies]
code-timing-macros.workspace = true
regex.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day-13-bench"
path = "benches/benchmarks.rs"
harness = false