[package]
name = "day-11"
version = "0.1.0"
edition = "2021"

[dependencies]
code-timing-macros.workspace = true
cached = "0.54.0"

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day-11-bench"
path = "benches/benchmarks.rs"
harness = false